freppledb/reportmanager/urls.py
#
# Copyright (C) 2019 by frePPLe bv
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

from django.urls import re_path

from freppledb import mode

# Automatically add these URLs when the application is installed
autodiscover = True

if mode == "WSGI":
    from . import views

    urlpatterns = [
        re_path(
            r"^reportmanager/schema/$",
            views.getSchema,
            name="reportmanager_schema",
        ),
        re_path(
            r"^reportmanager/(.+)/$",
            views.ReportManager.as_view(),
            name="reportmanager_id",
        ),
        re_path(
            r"^reportmanager/$",
            views.ReportManager.as_view(),
        ),
        re_path(
            r"^data/reportmanager/sqlreport/add/$",
            views.ReportManager.as_view(),
        ),
        re_path(
            r"^data/reportmanager/sqlreport/$",
            views.ReportList.as_view(),
        ),
    ]

freppledb/reportmanager/models.py
#
# Copyright (C) 2019 by frePPLe bv
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

from django.conf import settings
from django.db import models, DEFAULT_DB_ALIAS
from django.utils.translation import gettext_lazy as _

from freppledb.common.models import AuditModel, User, MultiDBManager
from freppledb.common.report import create_connection


class SQLReport(AuditModel):
    id = models.AutoField(_("identifier"), primary_key=True)
    name = models.CharField(_("name"), max_length=300, db_index=True)
    sql = models.TextField(_("SQL query"), null=True, blank=True)
    description = models.CharField(
        _("description"), max_length=1000, null=True, blank=True
    )
    user = models.ForeignKey(
        User,
        verbose_name=_("user"),
        blank=False,
        null=True,
        editable=False,
        related_name="reports",
        on_delete=models.CASCADE,
    )
    public = models.BooleanField(blank=True, default=False)

    def refreshColumns(self):
        from freppledb.common.middleware import _thread_locals

        req = getattr(_thread_locals, "request", None)
        if req:
            db = getattr(req, "database", DEFAULT_DB_ALIAS)
        else:
            db = getattr(_thread_locals, "database", DEFAULT_DB_ALIAS)
        SQLColumn.objects.filter(report=self).using(db).delete()
        if self.sql:
            conn = None
            try:
                conn = create_connection(db)
                with conn.cursor() as cursor:
                    sqlrole = settings.DATABASES[db].get("SQL_ROLE", "report_role")
                    if sqlrole:
                        cursor.execute("set role %s" % (sqlrole,))
                    # The query is limited to 1 row. We just need the column names at this point.
                    cursor.execute("select * from (%s) as Q limit 1" % self.sql)
                    if self.id:
                        cols = []
                        seq = 1
                        for f in cursor.description:
                            if f[0] in cols:
                                raise Exception("Duplicate column name '%s'" % f[0])
                            cols.append(f[0])
                            if f[1] == 1700:
                                fmt = "number"
                            elif f[1] == 1184:
                                fmt = "datetime"
                            elif f[1] in (23, 20):
                                fmt = "integer"
                            elif f[1] == 1186:
                                fmt = "duration"
                            elif f[1] == 1043:
                                fmt = "text"
                            else:
                                fmt = "character"
                            SQLColumn(
                                report=self, sequence=seq, name=f[0], format=fmt
                            ).save(using=db)
                            seq += 1
            finally:
                if conn:
                    conn.close()

    def save(self, *args, **kwargs):
        if self.sql and "pg_" in self.sql:
            raise Exception("Uhuh... What are trying to do?")
        if not self.id:
            self.refreshColumns()
        super().save(*args, **kwargs)
        self.refreshColumns()

    class Meta:
        db_table = "reportmanager_report"
        ordering = ("name",)
        verbose_name = _("my report")
        verbose_name_plural = _("my reports")

    def __str__(self):
        return self.name


class SQLColumn(models.Model):
    id = models.AutoField(_("identifier"), primary_key=True)
    report = models.ForeignKey(
        SQLReport,
        verbose_name="report",
        related_name="columns",
        on_delete=models.CASCADE,
    )
    sequence = models.IntegerField("sequence", default=1)
    name = models.CharField("name", max_length=300)
    format = models.CharField("format", max_length=20, null=True, blank=True)

    class Manager(MultiDBManager):
        def get_by_natural_key(self, report, sequence):
            return self.get(report=report, sequence=sequence)

    def natural_key(self):
        return (self.report, self.sequence)

    def __str__(self):
        return "%s.%s" % (self.report.name if self.report else "", self.name)

    class Meta:
        default_permissions = []
        db_table = "reportmanager_column"
        ordering = ("report", "sequence")
        unique_together = (("report", "sequence"),)
        verbose_name = "report column"
        verbose_name_plural = "report columns"

freppledb/reportmanager/templates/reportmanager/reportlist.html
{% extends "admin/base_site_grid.html" %}
{% load i18n %}

{% block extrahead %}{{block.super}}
<script>

var dont_show_related_objects_for_deletion = true;

function reportlink(cellvalue, options, row)
{
  return "<a href=\"" + url_prefix + "/reportmanager/" + row["id"] + "/\">"
      + cellvalue
      + "<span class='ps-2 fa fa-caret-right'></span></a><br>";
}
</script>
{% endblock %}

freppledb/reportmanager/templates/reportmanager/reportmanager.html
{% extends "admin/base_site_grid.html" %}
{% load i18n %}

{% block extrahead %}{{block.super}}

<script>

{% if perms.reportmanager.change_sqlreport or perms.reportmanager.add_sqlreport %}
function getSchema() {
   $.ajax({
      url: url_prefix + "/reportmanager/schema/",
      type: 'GET',
      datatype: "html",
      success: function(data) {
        $("#schemacolumn").html(data);
        $("#schemacolumn .schema-header").click(function() {
          $(this).children("span.fa").toggleClass("fa-plus").toggleClass("fa-minus");
          $(this).next(".collapse").collapse("toggle");
        });
        $("a.schemafield").on("click", function(e) {
          var field = $(e.target).closest("a").find("code").first().text();
          if (field != "") {
            var statements = $("#reportmanager_statements");
            if (statements[0].selectionStart || statements[0].selectionStart === 0) {
              var startPos = statements[0].selectionStart;
              var endPos = statements[0].selectionEnd;
              statements[0].value = statements[0].value.substring(0, startPos) +
                field + ", " +
                statements[0].value.substring(endPos, statements[0].value.length);
              statements[0].selectionStart = startPos + field.length + 2;
              statements[0].selectionEnd = startPos + field.length + 2;
            }
          else
            this.value += field + ", ";
          }
        });
      },
      async: true
      });
}

function startEdit() {
  $("#editreport, #editbuttons, #filterform").toggleClass("d-none");
  if ($("#schemacolumn").is(":empty")) getSchema();
}
{% endif %}

var xhr;

$(function() {

  $("#reportmanager_statements").resizable({
    handleSelector: "#resize-handle",
    resizeWidth: false,
    resizeHeight: true,
    onDrag: function(e) {
      $("#schemacolumn").height($("#reportmanager_statements").height());
    }
  });

  $("#reportmanager_statements").on("input", function() {
    $("#reportmanager_save").removeClass("btn-primary").addClass("btn-danger");
    $(window).on('beforeunload', function() {
      if ($("#reportmanager_save").hasClass("btn-danger"))
        return 'There are unsaved changes.';
    });
  });

  var id = {% if report %}{{report.id}}{% else %}0{% endif %};

  $("#reportmanager_save").on("click", function(event) {
    var data = {
        "sql": $("#reportmanager_statements").val(),
        "save": true,
        "name": $("#id_name").val(),
        "public": $("#id_public").is(":checked"),
        "description": $("#id_description").val()
        };
    if (id) data["id"] = id;
    xhr = $.ajax({
      url: url_prefix + "/reportmanager/",
      type: 'POST',
      dataType: 'json',
      data: data,
      async: true,
      success: function(data) {
      	if (data.status == "ok") {
          $("#reportmanager_save").addClass("btn-primary").removeClass("btn-danger");
          window.location.href = url_prefix + "/reportmanager/" + data.id + '/';
        }
      	else {
          $("#save_ok").remove();
          $("#workarea").prepend(
            '<div id="save_ok" class="row"><div class="col mt-2">'
            + '<div class="alert alert-danger">{% trans "Saving the report failed" %}&nbsp;:&nbsp;'
            + data.status
            + '</div></div>'
            );
      	}
      }
      });
  });

  $("#reportmanager_format").on("click", function(event) {
    var sql = $("#reportmanager_statements");
    var data = sql.val();
    xhr = $.ajax({
      url: url_prefix + "/reportmanager/",
      type: 'POST',
      dataType: 'json',
      data: {
        "sql": data,
        "format": true
        },
      success: function(data) {
        sql.val(data['formatted']);
      },
      async: true
      });
  });

  {% if report %}
  $("#reportmanager_delete").on("click", function(event) {
    xhr = $.ajax({
      url: url_prefix + "/reportmanager/",
      type: 'POST',
      data: {
        "id": {{report.id}},
        "delete": true
        },
      success: function() {
        window.location.href = url_prefix + "/data/reportmanager/sqlreport/";
      },
      async: true
      });
  });
  {% endif %}

  $("#reportmanager_cancel").on("click", function(event) {
    if (xhr) {
      xhr.abort();
      xhr = null;
      }
  });

  {% if not report %}
  getSchema();
  {% endif %}
});
</script>
{% endblock %}

{% block actions %}{{block.super}}
{% if perms.reportmanager.change_sqlreport or perms.reportmanager.add_sqlreport %}
<button class="btn btn-sm btn-primary" onclick="startEdit()" data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{% trans 'edit'|capfirst|force_escape %}" ><span class="fa fa-pencil"></span></button>
{% endif %}
{% endblock %}

{% block filter %}{% if report %}{{block.super}}{% endif %}{% endblock %}

{% block before_table %}

<div class="row form-group mb-0">

{% if perms.reportmanager.change_sqlreport %}
<div id="editbuttons" class="col-md-5{% if report %} d-none{% endif %}">
<button id="reportmanager_save" class="btn btn-primary">{% trans "save"|capfirst %}</button>
<button id="reportmanager_format" class="btn btn-primary">{% trans "format SQL query"|capfirst %}</button>
{% if report %}<button id="reportmanager_delete" class="btn btn-primary">{% trans "Delete" %}</button>{% endif %}
</div>
{% endif %}
</div>

<div id="editreport" {% if report %}class="d-none"{% endif %}>
<div class="row pt-2 pb-2">
<div class="col-form-label col-md-2" style="text-align:right">
  <label class="required" style="font-weight:bold; color:#333" for="id_name">{% trans "name"|capfirst %}:</label>
</div>
<div class="controls col-md-10">
  <input type="text" name="name" class="form-control vTextField" maxlength="300"
    placeholder="{% trans "name"|capfirst %}" value="{{report.name}}" required id="id_name">
</div>
</div>

<div class="row pt-2 pb-2">
<div class="col-form-label col-md-2" style="text-align:right">
  <label for="id_description">{% trans "description"|capfirst %}:</label>
</div>
<div class="controls col-md-10">
  <input type="text" name="description" class="form-control vTextField" maxlength="500"
    placeholder="{% trans "description"|capfirst %}" id="id_description"
    {% if report.description %}value="{{report.description}}"{% endif %}>
</div>
</div>

<div class="row pt-2 pb-2">
<div class="form-check-label col-md-2" style="text-align:right">
  <label for="id_public">{% trans "public"|capfirst %}:</label>
</div>
<div class="controls col-md-10">
  &nbsp;&nbsp;&nbsp;<input class="form-check-input" type="checkbox" style="transform: scale(1.5)" name="public" {% if report.public %}checked {% endif %}id="id_public">
</div>
</div>

<div class="row" style="text-align:center">
<div class="col-md-12">
<div id="sqlandschema" style="width:100%">
<table style="table-layout: fixed; width: 100%">
<tr>
<td style="padding-right: 5px">
<h5 style="text-align: left">{% trans "SQL query"|capfirst %}</h5>
<textarea id="reportmanager_statements" rows="10" class="form-control w-100"
 style="height:{% if request.prefs.height %}{{ request.prefs.height}}{% else %}200{% endif %}px; resize: none; font-size:1.25em; font-family:courier">
{{ report.sql }}
</textarea>
</td>
<td style="width:28em; padding-left:5px; padding-right:10px">
<h5>{% trans "schema"|capfirst %}</h5>
<div id="schemacolumn" style="overflow-y: scroll; height:{% if request.prefs.height %}{{ request.prefs.height}}{% else %}200{% endif %}px"></div>
</td>
</tr></table>
</div>
<span id="resize-handle" class="fa fa-bars handle" style="display: inline-block; touch-action: none"></span>
</div>
</div>

<!-- End editing section -->
</div>

{% endblock %}

freppledb/reportmanager/templates/reportmanager/schema.html
{% load i18n %}
<div class="col">
{% for m in schema %}
<div class="card">
    <div class="card-header schema-header" role="tab">
      <span class="fa fa-plus float-end panel-toggle"></span>
      <h5 class="name card-title" style="display: inline-block">
         <a role="button">{% trans "table"|capfirst %}&nbsp;{{ m.0 }}</a>
      </h5>
    </div>
    <div class="collapse card-body table-responsive schema-table">
        <table class="table table-sm table-hover">
            <thead>
            </thead>
            <tbody>
                {% for c in m.1 %}
                <tr>
                    <td width="50%"><a href="#" class="schemafield"><code>{{ c.0 }}</code>&nbsp;<span class="fa fa-clipboard"></span></a></td>
                    <td width="50%" class="text-muted"><small>{{ c.1 }}</small></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endfor %}
</div>